### ISSUE TITLE
다크모드 이미지 개선

### ISSUE THREAD

**Issue by brounyyyy** [Sevenwiki/issues#2]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/Sevenwiki/issues/issues)** to ensure this feature is not already requested.
- [X] This is a **feature request**, not a bug report.

### Describe the feature/enhancement

다크모드와 화이트 모드의 이미지 를 따로 만들어  가시성을 향상시키면 좋을것같습니다

### Use case / scenario

다크모드로 위키를 사용할 경우 투명 이미지가 잘 보이지 않을떄가 있습니다.
<img width="596" alt="20241123_234931" src="https://github.com/user-attachments/assets/a516194c-b78f-40bd-8459-93b1874355f9">
이를 개선한다면 어두운 투명이미지의 가시성을 향상시킬수 있을듯 합니다.

### Expected behavior

1. 다크모드로 사용할 경우 이미지의 윤곽을 자동으로 추가해주는 기능
2. 윤곽을 추가한 이미지를 따로 저장하여 다크모드 사용시 보여주는방식

**Comment by shiueo** [comment]
다크 모드일 때의 이미지와 화이트 모드일 때의 이미지를 각각 따로 설정할 수 있게 하는 것도 좋을 것 같네요. 해결 방안을 생각해 본 뒤 말씀드리겠습니다.
